#!/usr/bin/env python3
"""Generate mythos views/ from the faceted entry frontmatter.

Views are DERIVED. Do not hand-edit files in views/ — edit entries and re-run:
    python build-views.py
"""
import re
import pathlib
import collections

ROOT = pathlib.Path(__file__).parent
ENTRIES = ROOT / "entries"
VIEWS = ROOT / "views"
VIEWS.mkdir(exist_ok=True)

LIST_FIELDS = {"domain", "mode", "form", "geography", "tags"}
REGISTERS = ["conceptual", "material", "natural", "fictional", "virtual",
             "representational", "linguistic", "performative", "discursive"]
MODES = ["epistemological", "refusal", "embodiment", "duality", "cosmic-projection",
         "transformation", "hospitality", "scandal-power", "trickster",
         "uselessness-defied", "self-reference", "veneration", "found-form",
         "effigy", "reference-object", "formal-study", "proverbial",
         "scientific-object", "collection", "satire", "mechanism"]

GEN = "<!-- GENERATED by build-views.py — do not edit by hand; edit entries/ and re-run. -->\n"


def parse(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        return None
    fm = m.group(1)
    data = {"file": path.name}
    lines = fm.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        mm = re.match(r"^([A-Za-z][\w-]*):\s?(.*)$", line)
        if not mm:
            i += 1
            continue
        key, rest = mm.group(1), mm.group(2)
        if key == "links":
            edges = []
            j = i + 1
            while j < len(lines) and re.match(r"^\s*-\s*\{", lines[j]):
                em = re.search(r"to:\s*([\w-]+).*type:\s*([\w-]+)", lines[j])
                if em:
                    edges.append((em.group(1), em.group(2)))
                j += 1
            data["links"] = edges
            i = j
            continue
        if key in LIST_FIELDS:
            rest = rest.strip()
            if rest.startswith("[") and rest.endswith("]"):
                inner = rest[1:-1].strip()
                data[key] = [v.strip() for v in inner.split(",") if v.strip()] if inner else []
            else:
                data[key] = []
        else:
            v = rest.strip()
            if len(v) >= 2 and v[0] == '"' and v[-1] == '"':
                v = v[1:-1]
            data[key] = v.replace('\\"', '"').strip()
        i += 1
    data.setdefault("links", [])
    for f in LIST_FIELDS:
        data.setdefault(f, [])
    for s in ("name", "title", "ontology", "spout", "centrality", "stance", "year", "era"):
        data.setdefault(s, "")
    return data


entries = [e for e in (parse(p) for p in sorted(ENTRIES.glob("*.md"))) if e]
central = [e for e in entries if e.get("centrality") != "peripheral"]
peripheral = [e for e in entries if e.get("centrality") == "peripheral"]


def link(e):
    return f"[{e['title']}](../entries/{e['file']})"


def spout_badge(v):
    return {"yes": "**yes**", "no": "no", "n-a": "n-a"}.get(v, v or "—")


def write(name, text):
    (VIEWS / name).write_text(GEN + text, encoding="utf-8")


# ---- by-ontology -------------------------------------------------------------
def build_ontology():
    out = ["# Teapots by ontology (register of existence)\n",
           "The central/thesis axis. Each teapot's primary register of existence.\n"]
    for reg in REGISTERS:
        rows = [e for e in central if e.get("ontology") == reg]
        if not rows:
            continue
        out.append(f"\n## {reg}  ({len(rows)})\n")
        out.append("| Entry | Mode | spout | Era |")
        out.append("|---|---|---|---|")
        for e in sorted(rows, key=lambda x: x["name"]):
            out.append(f"| {link(e)} | {' · '.join(e['mode'])} | {spout_badge(e['spout'])} | {e['era'] or '—'} |")
    if peripheral:
        out.append("\n## peripheral (contrast set — fail the centrality gate)\n")
        out.append("| Entry | Ontology | Mode |")
        out.append("|---|---|---|")
        for e in sorted(peripheral, key=lambda x: x["name"]):
            out.append(f"| {link(e)} | {e['ontology']} | {' · '.join(e['mode'])} |")
    return "\n".join(out) + "\n"


# ---- by-mode -----------------------------------------------------------------
def build_mode():
    out = ["# Teapots by mode (symbolic function)\n",
           "The interpretive spine. Entries appear under every mode they carry.\n"]
    seen_modes = set()
    for mode in MODES:
        rows = [e for e in central if mode in e["mode"]]
        if not rows:
            continue
        seen_modes.add(mode)
        out.append(f"\n## {mode}  ({len(rows)})\n")
        for e in sorted(rows, key=lambda x: x["name"]):
            out.append(f"- {link(e)}  ·  _{e['ontology']}_  ·  spout: {e['spout']}")
    # any modes not in the ordered list
    extra = collections.Counter()
    for e in central:
        for md in e["mode"]:
            if md not in MODES:
                extra[md] += 1
    if extra:
        out.append("\n## (unlisted modes — add to schema vocab)\n")
        for md, n in extra.items():
            out.append(f"- {md} ({n})")
    return "\n".join(out) + "\n"


# ---- by-domain ---------------------------------------------------------------
def build_domain():
    out = ["# Teapots by domain (field of activity)\n"]
    by = collections.defaultdict(list)
    for e in central:
        for d in e["domain"]:
            by[d].append(e)
    for d in sorted(by, key=lambda k: (-len(by[k]), k)):
        out.append(f"\n## {d}  ({len(by[d])})\n")
        for e in sorted(by[d], key=lambda x: x["name"]):
            out.append(f"- {link(e)}  ·  _{e['ontology']}_")
    return "\n".join(out) + "\n"


# ---- by-spout ----------------------------------------------------------------
def build_spout():
    groups = {"yes": [], "no": [], "n-a": []}
    for e in central:
        groups.get(e["spout"], groups.setdefault(e["spout"], [])).append(e)
    out = ["# Teapots by spout — the spout hypothesis view\n",
           "Hypothesis: the teapot is the vessel defined by how it *gives out*. "
           "If true, `spout: yes` should cluster with material/duality/mechanism/"
           "physics/embodiment, and the conceptual/refusal teapots should be `no`.\n"]
    # cross-tab ontology x spout
    out.append("\n## Cross-tab: ontology × spout\n")
    out.append("| ontology | yes | no | n-a |")
    out.append("|---|---|---|---|")
    for reg in REGISTERS:
        rr = [e for e in central if e["ontology"] == reg]
        if not rr:
            continue
        y = sum(1 for e in rr if e["spout"] == "yes")
        n = sum(1 for e in rr if e["spout"] == "no")
        na = sum(1 for e in rr if e["spout"] == "n-a")
        out.append(f"| {reg} | {y} | {n} | {na} |")
    for g in ("yes", "no", "n-a"):
        rows = groups.get(g, [])
        out.append(f"\n## spout: {g}  ({len(rows)})\n")
        for e in sorted(rows, key=lambda x: x["name"]):
            out.append(f"- {link(e)}  ·  _{e['ontology']}_  ·  {' · '.join(e['mode'])}")
    return "\n".join(out) + "\n"


# ---- hypotheses (marquee) ----------------------------------------------------
def tagged(tag):
    return sorted([e for e in central if tag in e["tags"]], key=lambda x: x["name"])


def build_hypotheses():
    out = ["# Hypotheses & threads — the evidence view\n",
           f"Generated from {len(central)} central + {len(peripheral)} peripheral entries.\n"]

    # Spout
    ys = [e for e in central if e["spout"] == "yes"]
    ns = [e for e in central if e["spout"] == "no"]
    out.append("\n## 1. The spout hypothesis\n")
    out.append(f"**{len(ys)}** `spout: yes` vs **{len(ns)}** `spout: no`. "
               "The teapot read as the vessel defined by how it gives out.\n")
    out.append("\n`spout: yes` (the spout carries the meaning):\n")
    for e in ys:
        out.append(f"- {link(e)}  ·  _{e['ontology']}_  ·  {' · '.join(e['mode'])}")
    out.append("\nControl — the `conceptual` / `refusal` teapots, all `spout: no`:\n")
    for e in ns:
        if e["ontology"] in ("conceptual", "virtual") or "refusal" in e["mode"]:
            out.append(f"- {link(e)}  ·  _{e['ontology']}_  ·  {' · '.join(e['mode'])}")

    # Self-reference
    sn = tagged("self-naming")
    out.append("\n## 2. The self-reference hypothesis (the golden-braid nucleus)\n")
    out.append(f"**{len(sn)}** teapots that *name themselves*, linked by the "
               "`self-naming` tag rather than hard edges:\n")
    for e in sn:
        out.append(f"- {link(e)}  ·  _{e['ontology']}_  ·  {e.get('year') or '—'}")

    # Genealogy
    out.append("\n## 3. Genealogy — the typed link graph\n")
    incoming = collections.Counter()
    edges = []
    for e in central + peripheral:
        for to, typ in e["links"]:
            edges.append((e["name"], typ, to))
            incoming[to] += 1
    out.append("Edges (`from --type--> to`):\n")
    for frm, typ, to in sorted(edges):
        out.append(f"- `{frm}` **{typ}** `{to}`")
    if incoming:
        out.append("\nMost-pointed-at (roots everyone descends from):\n")
        for to, n in incoming.most_common(5):
            out.append(f"- `{to}` — {n} incoming")

    # char:arc
    out.append("\n## 4. Character arcs — service vs refusal\n")
    arcs = collections.defaultdict(list)
    for e in central:
        for t in e["tags"]:
            if t.startswith("char:arc-"):
                arcs[t.replace("char:arc-", "")].append(e)
    for arc in sorted(arcs):
        names = ", ".join(link(e) for e in sorted(arcs[arc], key=lambda x: x["name"]))
        out.append(f"- **{arc}**: {names}")

    # ontology-shift & motif clusters
    out.append("\n## 5. Motif clusters (emergent tag threads)\n")
    for tag in ("ontology-shift", "trick-vessel", "object-lifecycle", "celestial", "pareidolia", "namesake"):
        rows = tagged(tag)
        if rows:
            out.append(f"- **{tag}**: " + ", ".join(link(e) for e in rows))
    return "\n".join(out) + "\n"


# ---- index -------------------------------------------------------------------
def build_index():
    return ("# Views (generated)\n\n"
            f"Derived cross-sections of the {len(central)} central + {len(peripheral)} "
            "peripheral entries. **Do not hand-edit** — run `python build-views.py`.\n\n"
            "- [hypotheses.md](hypotheses.md) — evidence for the spout & self-reference theses, genealogy, char-arcs\n"
            "- [by-ontology.md](by-ontology.md) — the central register axis\n"
            "- [by-mode.md](by-mode.md) — the interpretive spine\n"
            "- [by-spout.md](by-spout.md) — the spout hypothesis cross-tab\n"
            "- [by-domain.md](by-domain.md) — field of activity\n"
            "- [gallery.html](gallery.html) — visual thumbnail gallery (view via GitHub Pages)\n")


# ---- image credits (written into assets/) ------------------------------------
def build_credits():
    rows = [e for e in entries if e.get("image")]
    out = ["# Image credits\n",
           f"{len(rows)} featured images, all freely licensed. CC-BY / CC-BY-SA require "
           "the attribution below; CC0 / public-domain require none.\n",
           "| Entry | File | License | Credit | Source |",
           "|---|---|---|---|---|"]
    for e in sorted(rows, key=lambda x: x["name"]):
        src = e.get("image_source", "")
        srclink = f"[file]({src})" if src else ""
        img = pathlib.Path(e.get("image", "")).name
        out.append(f"| {e['title']} | `{img}` | {e.get('image_license','')} | "
                   f"{e.get('image_credit','')} | {srclink} |")
    return "\n".join(out) + "\n"


write("README.md", build_index())
write("by-ontology.md", build_ontology())
write("by-mode.md", build_mode())
write("by-domain.md", build_domain())
write("by-spout.md", build_spout())
write("hypotheses.md", build_hypotheses())

(ROOT / "assets").mkdir(exist_ok=True)
(ROOT / "assets" / "CREDITS.md").write_text(GEN + build_credits(), encoding="utf-8")

print(f"images: {sum(1 for e in entries if e.get('image'))} (assets/CREDITS.md written)")
print(f"entries: {len(entries)} ({len(central)} central, {len(peripheral)} peripheral)")
print(f"spout yes/no/n-a: "
      f"{sum(1 for e in central if e['spout']=='yes')}/"
      f"{sum(1 for e in central if e['spout']=='no')}/"
      f"{sum(1 for e in central if e['spout']=='n-a')}")
print(f"self-naming: {len(tagged('self-naming'))}")
print("wrote:", ", ".join(sorted(p.name for p in VIEWS.glob('*.md'))))


# ---- images: thumbnails + static HTML gallery --------------------------------
ONTCOLOR = {
    "conceptual": "#6b5b95", "material": "#b5651d", "natural": "#4a7c59",
    "fictional": "#c1502e", "virtual": "#2a6f97", "representational": "#8e7cc3",
    "linguistic": "#c9a227", "performative": "#c2456e", "discursive": "#3a7ca5",
}
BLOB = "https://github.com/perrelet/teapots/blob/main/mythos/entries/"


def esc(s):
    return (s.replace("&", "&amp;").replace("<", "&lt;")
             .replace(">", "&gt;").replace('"', "&quot;"))


def build_thumbs():
    try:
        from PIL import Image
    except ImportError:
        print("Pillow missing; skipping thumbnails")
        return 0
    tdir = ROOT / "assets" / "thumbs"
    tdir.mkdir(parents=True, exist_ok=True)
    n = 0
    for e in entries:
        img = e.get("image", "")
        if not img or img.endswith(".svg"):
            continue
        dst = tdir / pathlib.Path(img).name
        try:
            im = Image.open(ROOT / img)
            im.thumbnail((400, 400))
            if dst.suffix.lower() in (".jpg", ".jpeg") and im.mode in ("RGBA", "P", "LA"):
                im = im.convert("RGB")
            im.save(dst)
            n += 1
        except Exception as ex:  # noqa
            print("thumb fail", img, ex)
    return n


def _thumb_src(e):
    img = e.get("image", "")
    if not img:
        return ""
    if img.endswith(".svg"):
        return "../" + img
    return "../assets/thumbs/" + pathlib.Path(img).name


GALLERY_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Teapot Mythos — gallery</title>
<style>
:root{--bg:#f7f3ec;--card:#fff;--ink:#2b2118;--muted:#7c6f60;--line:#e6ddcf;}
*{box-sizing:border-box}
body{margin:0;font:16px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:var(--bg);color:var(--ink)}
header{padding:28px 20px 8px;max-width:1200px;margin:0 auto}
h1{margin:0 0 4px;font-size:26px}
.sub{color:var(--muted);margin:0 0 14px}
.bar{display:flex;flex-wrap:wrap;gap:6px;align-items:center;max-width:1200px;margin:0 auto;padding:0 20px 6px}
.grouplabel{color:var(--muted);font-size:13px;margin-right:2px}
button.f,button.clear{cursor:pointer;border:1px solid var(--line);background:var(--card);color:var(--ink);border-radius:999px;padding:4px 11px;font-size:13px}
button.f{border-left:4px solid var(--c,#999)}
button.f.on{background:var(--c,#333);color:#fff;border-color:var(--c)}
button.clear{color:var(--muted)}
#q{border:1px solid var(--line);border-radius:999px;padding:5px 12px;font-size:13px;min-width:150px;background:var(--card);color:var(--ink)}
.count{color:var(--muted);font-size:13px;margin-left:auto}
main{max-width:1200px;margin:0 auto;padding:14px 20px 60px;display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:16px}
.card{display:flex;flex-direction:column;background:var(--card);border:1px solid var(--line);border-left:5px solid var(--c);border-radius:12px;overflow:hidden;text-decoration:none;color:inherit;transition:transform .12s,box-shadow .12s}
.card:hover{transform:translateY(-3px);box-shadow:0 8px 22px rgba(0,0,0,.10)}
.card.peripheral{border-style:dashed;opacity:.85}
.thumb{height:150px;background:#efe7da;display:flex;align-items:center;justify-content:center;overflow:hidden}
.thumb img{width:100%;height:100%;object-fit:cover}
.noimg{color:var(--muted);font-size:12px;font-style:italic}
.meta{padding:10px 12px 12px}
.meta h3{margin:0 0 6px;font-size:15px;line-height:1.25}
.badges{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:5px}
.ont{background:var(--c);color:#fff;border-radius:999px;padding:1px 8px;font-size:11px}
.sp{border:1px solid var(--line);border-radius:999px;padding:1px 8px;font-size:11px;color:var(--muted)}
.sp-yes{border-color:#b5651d;color:#b5651d}
.modes{color:var(--muted);font-size:12px}
@media (prefers-color-scheme:dark){:root{--bg:#181410;--card:#231d17;--ink:#f0e7db;--muted:#a89a88;--line:#3a3128}.thumb{background:#2c251d}}
</style>
</head>
<body>
<header>
<h1>&#129362; Teapot Mythos</h1>
<p class="sub">A faceted taxonomy of the teapot as a central object of human meaning-making. {{N}} entries &mdash; click any card to open its page.</p>
</header>
<div class="bar"><span class="grouplabel">ontology</span>{{ONTBTNS}}</div>
<div class="bar"><span class="grouplabel">spout</span>
<button class="f" data-k="spout" data-v="yes" style="--c:#b5651d">yes</button>
<button class="f" data-k="spout" data-v="no" style="--c:#999">no</button>
<button class="f" data-k="spout" data-v="n-a" style="--c:#999">n-a</button>
<button class="clear" id="clear">clear</button>
<input id="q" placeholder="search title">
<span class="count" id="count"></span>
</div>
<main id="grid">
{{CARDS}}
</main>
<script>
const cards=[...document.querySelectorAll('.card')];
const active={ont:new Set(),spout:new Set()};let q='';
function apply(){let n=0;for(const c of cards){
 const okOnt=!active.ont.size||active.ont.has(c.dataset.ont);
 const okSp=!active.spout.size||active.spout.has(c.dataset.spout);
 const okQ=!q||c.dataset.title.indexOf(q)>-1;
 const show=okOnt&&okSp&&okQ;c.style.display=show?'':'none';if(show)n++;}
 document.getElementById('count').textContent=n+' of '+cards.length;}
for(const b of document.querySelectorAll('button.f')){b.onclick=()=>{const k=b.dataset.k,v=b.dataset.v;
 if(active[k].has(v)){active[k].delete(v);b.classList.remove('on');}else{active[k].add(v);b.classList.add('on');}apply();};}
document.getElementById('clear').onclick=()=>{active.ont.clear();active.spout.clear();q='';document.getElementById('q').value='';
 document.querySelectorAll('button.f.on').forEach(b=>b.classList.remove('on'));apply();};
document.getElementById('q').oninput=e=>{q=e.target.value.toLowerCase();apply();};
apply();
</script>
</body>
</html>
"""


def build_gallery():
    rows = sorted(central + peripheral,
                  key=lambda x: (x.get("centrality") == "peripheral", x["name"]))
    cards = []
    for e in rows:
        col = ONTCOLOR.get(e["ontology"], "#888")
        ts = _thumb_src(e)
        peri = " peripheral" if e.get("centrality") == "peripheral" else ""
        t = esc(e["title"])
        dt = re.sub(r"[^a-z0-9 ]", "", e["title"].lower())
        inner = (f'<img loading="lazy" src="{ts}" alt="{t}">' if ts
                 else '<div class="noimg">no free image</div>')
        cards.append(
            f'<a class="card{peri}" href="{BLOB}{e["file"]}" '
            f'data-ont="{e["ontology"]}" data-mode="{" ".join(e["mode"])}" '
            f'data-spout="{e["spout"]}" data-title="{dt}" style="--c:{col}">'
            f'<div class="thumb">{inner}</div>'
            f'<div class="meta"><h3>{t}</h3>'
            f'<div class="badges"><span class="ont">{e["ontology"]}</span>'
            f'<span class="sp sp-{e["spout"]}">spout {e["spout"]}</span></div>'
            f'<div class="modes">{" &middot; ".join(e["mode"])}</div></div></a>')
    onts = sorted(set(e["ontology"] for e in central))
    ontbtns = "".join(
        f'<button class="f" data-k="ont" data-v="{o}" style="--c:{ONTCOLOR.get(o, "#888")}">{o}</button>'
        for o in onts)
    return (GALLERY_TEMPLATE
            .replace("{{CARDS}}", "\n".join(cards))
            .replace("{{ONTBTNS}}", ontbtns)
            .replace("{{N}}", str(len(rows))))


_t = build_thumbs()
(VIEWS / "gallery.html").write_text(build_gallery(), encoding="utf-8")
print(f"thumbs: {_t}; gallery.html written ({len(central) + len(peripheral)} cards)")
