#!/usr/bin/env python3
"""Generate mythos views/ from the faceted entry frontmatter.

Views are DERIVED. Do not hand-edit files in views/ — edit entries and re-run:
    python build-views.py
"""
import re
import pathlib
import collections

ROOT = pathlib.Path(__file__).parent
ENTRIES = ROOT / "entries"
VIEWS = ROOT / "views"
VIEWS.mkdir(exist_ok=True)

LIST_FIELDS = {"domain", "mode", "form", "geography", "tags"}
REGISTERS = ["conceptual", "material", "natural", "fictional", "virtual",
             "representational", "linguistic", "performative", "discursive"]
MODES = ["epistemological", "refusal", "embodiment", "duality", "cosmic-projection",
         "transformation", "hospitality", "scandal-power", "trickster",
         "uselessness-defied", "self-reference", "veneration", "found-form",
         "effigy", "reference-object", "formal-study", "proverbial",
         "scientific-object", "collection", "satire", "mechanism"]

GEN = "<!-- GENERATED by build-views.py — do not edit by hand; edit entries/ and re-run. -->\n"


def parse(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        return None
    fm = m.group(1)
    data = {"file": path.name}
    lines = fm.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        mm = re.match(r"^([A-Za-z][\w-]*):\s?(.*)$", line)
        if not mm:
            i += 1
            continue
        key, rest = mm.group(1), mm.group(2)
        if key == "links":
            edges = []
            j = i + 1
            while j < len(lines) and re.match(r"^\s*-\s*\{", lines[j]):
                em = re.search(r"to:\s*([\w-]+).*type:\s*([\w-]+)", lines[j])
                if em:
                    edges.append((em.group(1), em.group(2)))
                j += 1
            data["links"] = edges
            i = j
            continue
        if key in LIST_FIELDS:
            rest = rest.strip()
            if rest.startswith("[") and rest.endswith("]"):
                inner = rest[1:-1].strip()
                data[key] = [v.strip() for v in inner.split(",") if v.strip()] if inner else []
            else:
                data[key] = []
        else:
            v = rest.strip()
            if len(v) >= 2 and v[0] == '"' and v[-1] == '"':
                v = v[1:-1]
            data[key] = v.replace('\\"', '"').strip()
        i += 1
    data.setdefault("links", [])
    for f in LIST_FIELDS:
        data.setdefault(f, [])
    for s in ("name", "title", "ontology", "spout", "centrality", "stance", "year", "era"):
        data.setdefault(s, "")
    return data


entries = [e for e in (parse(p) for p in sorted(ENTRIES.glob("*.md"))) if e]
central = [e for e in entries if e.get("centrality") != "peripheral"]
peripheral = [e for e in entries if e.get("centrality") == "peripheral"]


def link(e):
    return f"[{e['title']}](../entries/{e['file']})"


def spout_badge(v):
    return {"yes": "**yes**", "no": "no", "n-a": "n-a"}.get(v, v or "—")


def write(name, text):
    (VIEWS / name).write_text(GEN + text, encoding="utf-8")


# ---- by-ontology -------------------------------------------------------------
def build_ontology():
    out = ["# Teapots by ontology (register of existence)\n",
           "The central/thesis axis. Each teapot's primary register of existence.\n"]
    for reg in REGISTERS:
        rows = [e for e in central if e.get("ontology") == reg]
        if not rows:
            continue
        out.append(f"\n## {reg}  ({len(rows)})\n")
        out.append("| Entry | Mode | spout | Era |")
        out.append("|---|---|---|---|")
        for e in sorted(rows, key=lambda x: x["name"]):
            out.append(f"| {link(e)} | {' · '.join(e['mode'])} | {spout_badge(e['spout'])} | {e['era'] or '—'} |")
    if peripheral:
        out.append("\n## peripheral (contrast set — fail the centrality gate)\n")
        out.append("| Entry | Ontology | Mode |")
        out.append("|---|---|---|")
        for e in sorted(peripheral, key=lambda x: x["name"]):
            out.append(f"| {link(e)} | {e['ontology']} | {' · '.join(e['mode'])} |")
    return "\n".join(out) + "\n"


# ---- by-mode -----------------------------------------------------------------
def build_mode():
    out = ["# Teapots by mode (symbolic function)\n",
           "The interpretive spine. Entries appear under every mode they carry.\n"]
    seen_modes = set()
    for mode in MODES:
        rows = [e for e in central if mode in e["mode"]]
        if not rows:
            continue
        seen_modes.add(mode)
        out.append(f"\n## {mode}  ({len(rows)})\n")
        for e in sorted(rows, key=lambda x: x["name"]):
            out.append(f"- {link(e)}  ·  _{e['ontology']}_  ·  spout: {e['spout']}")
    # any modes not in the ordered list
    extra = collections.Counter()
    for e in central:
        for md in e["mode"]:
            if md not in MODES:
                extra[md] += 1
    if extra:
        out.append("\n## (unlisted modes — add to schema vocab)\n")
        for md, n in extra.items():
            out.append(f"- {md} ({n})")
    return "\n".join(out) + "\n"


# ---- by-domain ---------------------------------------------------------------
def build_domain():
    out = ["# Teapots by domain (field of activity)\n"]
    by = collections.defaultdict(list)
    for e in central:
        for d in e["domain"]:
            by[d].append(e)
    for d in sorted(by, key=lambda k: (-len(by[k]), k)):
        out.append(f"\n## {d}  ({len(by[d])})\n")
        for e in sorted(by[d], key=lambda x: x["name"]):
            out.append(f"- {link(e)}  ·  _{e['ontology']}_")
    return "\n".join(out) + "\n"


# ---- by-spout ----------------------------------------------------------------
def build_spout():
    groups = {"yes": [], "no": [], "n-a": []}
    for e in central:
        groups.get(e["spout"], groups.setdefault(e["spout"], [])).append(e)
    out = ["# Teapots by spout — the spout hypothesis view\n",
           "Hypothesis: the teapot is the vessel defined by how it *gives out*. "
           "If true, `spout: yes` should cluster with material/duality/mechanism/"
           "physics/embodiment, and the conceptual/refusal teapots should be `no`.\n"]
    # cross-tab ontology x spout
    out.append("\n## Cross-tab: ontology × spout\n")
    out.append("| ontology | yes | no | n-a |")
    out.append("|---|---|---|---|")
    for reg in REGISTERS:
        rr = [e for e in central if e["ontology"] == reg]
        if not rr:
            continue
        y = sum(1 for e in rr if e["spout"] == "yes")
        n = sum(1 for e in rr if e["spout"] == "no")
        na = sum(1 for e in rr if e["spout"] == "n-a")
        out.append(f"| {reg} | {y} | {n} | {na} |")
    for g in ("yes", "no", "n-a"):
        rows = groups.get(g, [])
        out.append(f"\n## spout: {g}  ({len(rows)})\n")
        for e in sorted(rows, key=lambda x: x["name"]):
            out.append(f"- {link(e)}  ·  _{e['ontology']}_  ·  {' · '.join(e['mode'])}")
    return "\n".join(out) + "\n"


# ---- hypotheses (marquee) ----------------------------------------------------
def tagged(tag):
    return sorted([e for e in central if tag in e["tags"]], key=lambda x: x["name"])


def build_hypotheses():
    out = ["# Hypotheses & threads — the evidence view\n",
           f"Generated from {len(central)} central + {len(peripheral)} peripheral entries.\n"]

    # Spout
    ys = [e for e in central if e["spout"] == "yes"]
    ns = [e for e in central if e["spout"] == "no"]
    out.append("\n## 1. The spout hypothesis\n")
    out.append(f"**{len(ys)}** `spout: yes` vs **{len(ns)}** `spout: no`. "
               "The teapot read as the vessel defined by how it gives out.\n")
    out.append("\n`spout: yes` (the spout carries the meaning):\n")
    for e in ys:
        out.append(f"- {link(e)}  ·  _{e['ontology']}_  ·  {' · '.join(e['mode'])}")
    out.append("\nControl — the `conceptual` / `refusal` teapots, all `spout: no`:\n")
    for e in ns:
        if e["ontology"] in ("conceptual", "virtual") or "refusal" in e["mode"]:
            out.append(f"- {link(e)}  ·  _{e['ontology']}_  ·  {' · '.join(e['mode'])}")

    # Self-reference
    sn = tagged("self-naming")
    out.append("\n## 2. The self-reference hypothesis (the golden-braid nucleus)\n")
    out.append(f"**{len(sn)}** teapots that *name themselves*, linked by the "
               "`self-naming` tag rather than hard edges:\n")
    for e in sn:
        out.append(f"- {link(e)}  ·  _{e['ontology']}_  ·  {e.get('year') or '—'}")

    # Genealogy
    out.append("\n## 3. Genealogy — the typed link graph\n")
    incoming = collections.Counter()
    edges = []
    for e in central + peripheral:
        for to, typ in e["links"]:
            edges.append((e["name"], typ, to))
            incoming[to] += 1
    out.append("Edges (`from --type--> to`):\n")
    for frm, typ, to in sorted(edges):
        out.append(f"- `{frm}` **{typ}** `{to}`")
    if incoming:
        out.append("\nMost-pointed-at (roots everyone descends from):\n")
        for to, n in incoming.most_common(5):
            out.append(f"- `{to}` — {n} incoming")

    # char:arc
    out.append("\n## 4. Character arcs — service vs refusal\n")
    arcs = collections.defaultdict(list)
    for e in central:
        for t in e["tags"]:
            if t.startswith("char:arc-"):
                arcs[t.replace("char:arc-", "")].append(e)
    for arc in sorted(arcs):
        names = ", ".join(link(e) for e in sorted(arcs[arc], key=lambda x: x["name"]))
        out.append(f"- **{arc}**: {names}")

    # ontology-shift & motif clusters
    out.append("\n## 5. Motif clusters (emergent tag threads)\n")
    for tag in ("ontology-shift", "trick-vessel", "object-lifecycle", "celestial", "pareidolia", "namesake"):
        rows = tagged(tag)
        if rows:
            out.append(f"- **{tag}**: " + ", ".join(link(e) for e in rows))
    return "\n".join(out) + "\n"


# ---- index -------------------------------------------------------------------
def build_index():
    return ("# Views (generated)\n\n"
            f"Derived cross-sections of the {len(central)} central + {len(peripheral)} "
            "peripheral entries. **Do not hand-edit** — run `python build-views.py`.\n\n"
            "- [hypotheses.md](hypotheses.md) — evidence for the spout & self-reference theses, genealogy, char-arcs\n"
            "- [by-ontology.md](by-ontology.md) — the central register axis\n"
            "- [by-mode.md](by-mode.md) — the interpretive spine\n"
            "- [by-spout.md](by-spout.md) — the spout hypothesis cross-tab\n"
            "- [by-domain.md](by-domain.md) — field of activity\n")


write("README.md", build_index())
write("by-ontology.md", build_ontology())
write("by-mode.md", build_mode())
write("by-domain.md", build_domain())
write("by-spout.md", build_spout())
write("hypotheses.md", build_hypotheses())

print(f"entries: {len(entries)} ({len(central)} central, {len(peripheral)} peripheral)")
print(f"spout yes/no/n-a: "
      f"{sum(1 for e in central if e['spout']=='yes')}/"
      f"{sum(1 for e in central if e['spout']=='no')}/"
      f"{sum(1 for e in central if e['spout']=='n-a')}")
print(f"self-naming: {len(tagged('self-naming'))}")
print("wrote:", ", ".join(sorted(p.name for p in VIEWS.glob('*.md'))))
